import home from './home.svg'
import file from './file.svg'
import briefcase from './briefcase.svg'
import message from './message.svg'
import user from './user.svg'
import bg from './background.jpg'
import me from './yo.png'
import javaScript from './javascript-color.svg'
import react from './react-color.svg'
import html from './html5-color.svg'
import css from './css3-color.svg'
import tailwind from './tailwindcss-color.svg'
import uxf from './uxfinity.png'
import pocket from './pocketpal.png'
import rally from './rallyfund.png'
import concept from './concept.png'
import instagram from './instagram.svg'
import linkedin from './linkedin.svg'
import love from './love.svg'

export { love, home, file, briefcase, me, message, user, bg, javaScript, react, html, css, tailwind, uxf, pocket, rally, concept, instagram, linkedin }
